version: '3'

services:

   api:
     container_name: text-compare
     build: .
     ports:
       - "8008:80"
     volumes:
       - ./web-server:/usr/src/app/web-server
     restart: unless-stopped
